### ISSUE TITLE
Add support for arm64 images

### ISSUE THREAD

**Issue by timuthy** [gardener/vpn2#8]
**What would you like to be added**:
Images build and published through this repository are only amd64 compatible. We should enable a multi-arch docker build to also offer arm64 images.

**Why is this needed**:
To run seeds/shoots on arm64 based hardware. In addition, more and more developers work with Apple Silicon based machines and an arm64 based image is required to use the [local provider setup](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md).

**Comment by rfranzke** [comment]
cc @PavelPavlov46 @ccwienk
